title = "Azure Security"
# baseURL = "https://nishanthkp.gitlab.io/azure-security-reva/"
baseURL = "/"
languageCode = "en-us"

theme = "hugo-theme-learn"
uglyurls = true


[outputs]
home = [ "HTML", "RSS", "JSON"]


[params]
showVisitedLinks = true

