title = "Azure Security"
baseURL = "https://nishanthkp.gitlab.io/azure-security-reva/"
languageCode = "en-us"

theme = "hugo-theme-learn"
uglyurls = true


[outputs]
home = [ "HTML", "RSS", "JSON"]



